- name: bootstrap fully encrypted linux image
  when: hetzner_autoinstall|default(false)
  block:
  - name: copy setup.conf template
    template:
      src: setup.conf
      dest: "{{ autoinstall_setup_conf_dest }}"
  
  - name: copy post install script
    template:
      src: post-install.sh
      dest: "{{ autoinstall_post_install_dest }}"
      owner: root
      mode: "0755"
  
  - name: copy authorized_keys
    copy:
      src: "{{ autoinstall_authorized_keys_src }}"
      dest: "{{ autoinstall_authorized_keys_dest }}"
  
  - name: run autoinstall
    shell: "/root/.oldroot/nfs/install/installimage -a -c {{ autoinstall_setup_conf_dest }} -x {{ autoinstall_post_install_dest }}"

  - name: reboot
    reboot:
