---

- name: download install sets for sysupgrade
  become: yes
  shell: "sysupgrade -n {{ sysupgrade_openbsd_args }}"
  register: sysupgrade_task
  changed_when: "'Will upgrade on next reboot' in sysupgrade_task.stdout"

- name: wait for upgrade to finish
  become: yes
  reboot:
    reboot_timeout: 900
  when: sysupgrade_task.changed

