- name: Install or update required packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - apparmor
    - apparmor-utils
  become: yes
  when: ansible_distribution|lower == 'debian'

- name: run cluster init on first node
  shell: "curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_master_token }} sh -s - server --cluster-init --node-ip {{ k3s_node_address }} --flannel-iface {{ k3s_node_interface }}"
  when: k3s_bootstrap
