---
- name: wg-reload
  systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: yes
  become: yes
- name: iptables-save-ubuntu
  command: netfilter-persistent save
  become: yes

- name: openbsd-wg-reload
  shell: "sh /etc/netstart {{ wg_if }}"
  become: yes
