- name: restart registry
  command: docker stop registry
  notify: restart registry (start)
- name: restart registry (start)
  command: docker run -d -p 5000:5000 --restart=always --name registry \
             -v /etc/docker/registry/config.yml:/etc/docker/registry/config.yml \
             registry:2
